POST http://localhost:5000/api/users/register
content-type: application/json

{
    "email": "august944@gmail.com",
    "password": "1234",
    "confirmPassword": "1234"
}
####
POST http://localhost:5000/api/users/login
content-type: application/json

{
    "email": "august944@gmail.com",
    "password": "1234"
}

###
POST http://localhost:5000/api/users/refresh
content-type: application/json

###
GET http://localhost:5000/api/users/me
content-type: application/json


####
POST http://localhost:5000/api/users/logout

####
GET http://localhost:5000/api/clients

###
GET http://localhost:5000/api/clients/625c71fa7cc6a3c00dff30bf

###
GET http://localhost:5000/api/lol

###
DELETE http://localhost:5000/api/clients/624d69e49018fd0cf6d6ee5d

####
POST http://localhost:5000/api/clients
content-type: application/json

{
    "name": "Kinga",
    "category": "event",
    "date": "2021-11-20T12:05:45",
    "value": 4000,
    "alreadyPaid": 100,
    "status": "Completed",
    "address": "Kalisz, czestochowska 69/62",
    "info": "To sa dodatkowe informacje"
}

###
PUT http://localhost:5000/api/clients/625009f420ad00bab0c38281
content-type: application/json

{
    "name": "nowypoprawionyeeeole",
    "category": "event",
    "date": "2021-11-20T12:05:45",
    "value": 5000,
    "alreadyPaid": 500,
    "status": "Leady",
    "address": "Kaliszda, czestochowska 69/62",
    "info": "To sa dodatkowe informacje"
}


###
GET http://localhost:5000/api/tasks

###
POST http://localhost:5000/api/tasks
content-type: application/json

{
    "name": "nowy task2",
    "priority": "medium"
}
###
DELETE http://localhost:5000/api/tasks/624d93124cbf903cbab03139

###
PUT http://localhost:5000/api/tasks/624d959d4dacfcad74be3a94
content-type: application/json

{
    "name": "nowy task1edited",
    "priority": "high"
}